ToString Function Implemented
mit-dci/libutreexo pull request #11
Opened 2022-03-15 07:27 UTC by sudhnsh

ToString function of utreexo which was in forest.go was implemented in ram_forest.cpp

2022-03-15 07:36 UTC, kcalvinalvin commented
Could you add the following code in ```accumulator_tests.cpp```

```
BOOST_AUTO_TEST_CASE(tostring) {
    RamForest full(0);

    std::vector<Leaf> leaves;
    CreateTestLeaves(leaves, 8);

    BOOST_CHECK(full.Modify(unused_undo, leaves, {}));

    ForestState state(8);
    std::cout << full.tostring(state) << std::endl;;
}
```

The code fails when ran with this test. You can run the test by building the code with `make all`, then running this command: `./test-verify --run_test=accumulator_tests/tostring`

2022-03-15 07:39 UTC, kcalvinalvin commented on src/ram_forest.cpp
> +std::string RamForest::tostring(const ForestState& f)
We should be initializing the ForestState inside this function instead of having the caller passing it in.

2022-03-15 09:29 UTC, dergoegge requested changes
Thank you for this!

I took a first glance and left some comments for you. 
Please squash your commits into one.

2022-03-15 09:29 UTC, dergoegge commented on include/ram_forest.h
> +    std::string tostring(const ForestState& f);
```suggestion
    std::string ToString(const ForestState& f) const;
```

2022-03-15 09:29 UTC, dergoegge commented on src/ram_forest.cpp
> +        std::string s = "can't Print" + std::to_string(f.m_num_leaves) + "Leaves. Roots:\n";
```suggestion
        std::string s = "can't print" + std::to_string(f.m_num_leaves) + "leaves. roots:\n";
```

2022-03-15 09:29 UTC, dergoegge commented on src/ram_forest.cpp
> +    uint8_t fh = f.NumRows();
I know the go implementation uses the same names, but would you mind finding more descriptive names for the variables in this function?

2022-03-15 09:29 UTC, dergoegge commented on src/ram_forest.cpp
> +        unsigned int rowlen = (1 << (fh - h));
I try to use the coding style recommend in the [Bitcoin Core developer docs](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#coding-style-c).
```suggestion
        unsigned int row_length = (1 << (fh - h));
```

2022-03-15 11:22 UTC, sudhnsh commented on src/ram_forest.cpp
> +        unsigned int rowlen = (1 << (fh - h));
I made all the changes that you requested. Thank you.

2022-03-15 11:32 UTC, kcalvinalvin commented
I think the test is failing to build because `ToString()` makes the caller pass in `ForestState`. So you need to put `#include "state.h"` in `accumulator_tests.cpp` for the build to pass.

Since all you need to initalize the `ForestState` is `m_num_leaves`, you could just do it inside the function and there'd be no need to put that include.

2022-03-15 11:34 UTC, sudhnsh commented
> I think the test is failing to build because `ToString()` makes the caller pass in `ForestState`. So you need to put `#include "state.h"` in `accumulator_tests.cpp` for the build to pass.
> 
> Since all you need to initalize the `ForestState` is `m_num_leaves`, you could just do it inside the function and there'd be no need to put that include.

Sorry, I forgot that, it's included now.

2022-03-15 11:34 UTC, kcalvinalvin commented
Also, could you [squash](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits) your commits.

2022-03-17 11:59 UTC, kcalvinalvin commented
The forest isn't being printed right. I get this when printing:

```
[I] calvin@bitcoin ~/b/c/l/libutreexo ((184d7dc9…))> ./test-verify --run_test=accumulator_tests/ToString
Running 1 test case...
       
|-------------------------------\                                                                             
              
|---------------\                                   |---------------\                                   
8:23122                      
|-------\              |-------\              |-------\              |-------\              
0:00 1:10 2:20 3:30 4:40 5:50 6:60 7:70 
```

Also, you haven't addressed: squashing commits, removing the need for the caller to pass in `ForestState`

2022-03-17 21:41 UTC, closed without merging